# Site settings
title: Amazing Blog Template
description: > # this means to ignore newlines until "baseurl:"
  This is a personal portfolio website designed and developed by Jiadong Wu and Liu Han in
  University of Pittsburgh.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://portfolio.wuplus.net/" # the base hostname & protocol for your site

# About Page Setting
aboutDescription: > # this means to ignore newlines until "baseurl:"
  Hi, There. 
  I am a master student of University of Pittsburgh interested in front end
  developing.

# Contact Page Setting
twitter_url: https://twitter.com/wuplus
email: wuplus1992@gmail.com
facebook_url: http://facebook.com
linkedin_url: https://www.linkedin.com/in/jiw1992
github_url: https://github.com/InternetFarmer

# Build settings
markdown: kramdown
